name: 🐛 Bug Report - 错误报告
description: 报告一个bug来帮助我们改进
title: "[Bug]: "
labels: ["bug", "triage"]
assignees:
  - your-username

body:
  - type: markdown
    attributes:
      value: |
        感谢您花时间填写这个bug报告！请提供尽可能多的信息来帮助我们重现和修复问题。

  - type: textarea
    id: bug-description
    attributes:
      label: 🐛 Bug描述
      description: 清晰简洁地描述这个bug是什么
      placeholder: 请详细描述遇到的问题...
    validations:
      required: true

  - type: textarea
    id: reproduction-steps
    attributes:
      label: 🔄 重现步骤
      description: 重现此行为的步骤
      placeholder: |
        1. 访问 '...'
        2. 点击 '....'
        3. 滚动到 '....'
        4. 看到错误
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: ✅ 预期行为
      description: 清晰简洁地描述您期望发生什么
      placeholder: 我期望...
    validations:
      required: true

  - type: textarea
    id: actual-behavior
    attributes:
      label: ❌ 实际行为
      description: 清晰简洁地描述实际发生了什么
      placeholder: 实际上...
    validations:
      required: true

  - type: textarea
    id: screenshots
    attributes:
      label: 📸 截图
      description: 如果适用，添加截图来帮助解释您的问题
      placeholder: 拖拽截图到这里...

  - type: dropdown
    id: severity
    attributes:
      label: 🚨 严重程度
      description: 这个bug对您的工作影响有多大？
      options:
        - 低 - 小问题，有变通方法
        - 中 - 影响功能，但系统仍可使用
        - 高 - 主要功能不可用
        - 紧急 - 系统完全不可用
    validations:
      required: true

  - type: dropdown
    id: component
    attributes:
      label: 🎯 影响组件
      description: 哪个组件受到影响？
      options:
        - Web界面
        - 数据分析引擎
        - 报告生成系统
        - 可视化模块
        - WebSocket通信
        - 数据库
        - 认证系统
        - API接口
        - Docker部署
        - CI/CD流水线
        - 其他
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: 📦 版本信息
      description: 您使用的是哪个版本？
      placeholder: v3.4.0
    validations:
      required: true

  - type: dropdown
    id: environment
    attributes:
      label: 🌐 运行环境
      description: 问题发生在哪个环境？
      options:
        - 开发环境
        - 测试环境
        - 生产环境
        - Docker容器
        - 本地运行
    validations:
      required: true

  - type: textarea
    id: system-info
    attributes:
      label: 💻 系统信息
      description: 请提供系统信息
      value: |
        - OS: [例如 Ubuntu 20.04, Windows 10, macOS 12.0]
        - Browser: [例如 Chrome 95, Firefox 94, Safari 15]
        - Python版本: [例如 3.11.0]
        - Docker版本: [例如 20.10.12]
        - 内存: [例如 8GB]
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: 📝 相关日志
      description: 请粘贴任何相关的日志输出
      placeholder: |
        请在这里粘贴错误日志、堆栈跟踪或其他相关信息...
        
        您可以通过以下方式获取日志：
        - docker-compose logs app
        - 浏览器开发者工具控制台
        - 系统日志文件

  - type: textarea
    id: additional-context
    attributes:
      label: 📋 额外信息
      description: 添加任何其他关于问题的上下文信息
      placeholder: 任何其他可能有助于诊断问题的信息...

  - type: checkboxes
    id: terms
    attributes:
      label: ✅ 确认事项
      description: 在提交之前，请确认以下事项
      options:
        - label: 我已经搜索了现有的issues，确认这不是重复报告
          required: true
        - label: 我已经提供了足够的信息来重现这个问题
          required: true
        - label: 我已经检查了文档，确认这不是预期行为
          required: true
        - label: 如果这是安全问题，我已经通过私人渠道报告而不是公开issue
          required: true